/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AlbumSearchPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  folder: "Albums",
  fileNameFormat: "{{title}}",
  templateFile: "",
  spotifyClientId: "",
  spotifyClientSecret: ""
};
var AlbumSearchPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.accessToken = "";
    this.tokenExpiry = 0;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "search-album",
      name: "Search Album",
      callback: () => {
        if (!this.settings.spotifyClientId || !this.settings.spotifyClientSecret) {
          new import_obsidian.Notice(
            "Please set your Spotify Client ID and Secret in settings."
          );
          return;
        }
        new AlbumSearchModal(this.app, this).open();
      }
    });
    this.addSettingTab(new AlbumSearchSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async getSpotifyToken() {
    if (this.accessToken && Date.now() < this.tokenExpiry) {
      return this.accessToken;
    }
    try {
      const authString = btoa(
        `${this.settings.spotifyClientId}:${this.settings.spotifyClientSecret}`
      );
      const response = await (0, import_obsidian.requestUrl)({
        url: "https://accounts.spotify.com/api/token",
        method: "POST",
        headers: {
          Authorization: `Basic ${authString}`,
          "Content-Type": "application/x-www-form-urlencoded"
        },
        body: "grant_type=client_credentials"
      });
      if (response.status === 200) {
        const data = response.json;
        this.accessToken = data.access_token;
        this.tokenExpiry = Date.now() + (data.expires_in - 60) * 1e3;
        return this.accessToken;
      } else {
        console.error("Spotify Auth Failed:", response);
        new import_obsidian.Notice("Failed to authenticate with Spotify.");
        return null;
      }
    } catch (error) {
      console.error("Spotify Auth Error:", error);
      new import_obsidian.Notice("Error authenticating with Spotify.");
      return null;
    }
  }
};
var AlbumSearchModal = class extends import_obsidian.SuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("Search for an album...");
  }
  async getSuggestions(query) {
    if (query === "") {
      return [];
    }
    const token = await this.plugin.getSpotifyToken();
    if (!token)
      return [];
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `https://api.spotify.com/v1/search?q=${encodeURIComponent(
          query
        )}&type=album&limit=20`,
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      if (response.status === 200) {
        return response.json.albums.items;
      } else {
        new import_obsidian.Notice("Failed to search Spotify.");
        return [];
      }
    } catch (error) {
      console.error("Spotify Search Error:", error);
      return [];
    }
  }
  renderSuggestion(album, el) {
    const container = el.createDiv({
      cls: "album-search-suggestion"
    });
    const imageUrl = album.images.length > 0 ? album.images[album.images.length - 1].url : "";
    if (imageUrl) {
      const img = container.createEl("img", {
        attr: { src: imageUrl },
        cls: "album-cover-thumbnail"
      });
    }
    const text = container.createDiv({ cls: "album-info" });
    text.createDiv({ text: album.name, cls: "album-name" });
    const artistName = album.artists.map((a) => a.name).join(", ");
    text.createDiv({ text: artistName, cls: "album-artist" });
    const year = album.release_date ? album.release_date.substring(0, 4) : "";
    text.createDiv({ text: year, cls: "album-year" });
  }
  async onChooseSuggestion(album, evt) {
    new import_obsidian.Notice(`Selected: ${album.name}`);
    await this.createAlbumNote(album);
  }
  async createAlbumNote(album) {
    const folderPath = this.plugin.settings.folder;
    const fileNameFormat = this.plugin.settings.fileNameFormat || DEFAULT_SETTINGS.fileNameFormat;
    if (!this.plugin.app.vault.getAbstractFileByPath(folderPath)) {
      await this.plugin.app.vault.createFolder(folderPath);
    }
    const largeCoverUrl = album.images.length > 0 ? album.images[0].url : "";
    const artistName = album.artists.map((a) => a.name).join(", ");
    const year = album.release_date ? album.release_date.substring(0, 4) : "";
    const date = (0, import_obsidian.moment)().format("YYYY-MM-DD");
    const variables = {
      "{{title}}": album.name,
      "{{artist}}": artistName,
      "{{year}}": year,
      "{{date}}": date,
      "{{cover}}": largeCoverUrl,
      "{{coverUrl}}": largeCoverUrl,
      "{{publishYear}}": year,
      "{{genre}}": "Pop",
      // Spotify API doesn't return genre on Album object easily without extra calls, defaulted or empty
      "{{tracks}}": String(album.total_tracks),
      "{{url}}": album.external_urls.spotify,
      "{{id}}": album.id
    };
    let filename = fileNameFormat;
    for (const key in variables) {
      filename = filename.replace(
        new RegExp(key, "g"),
        this.sanitizeFileName(variables[key])
      );
    }
    filename = this.sanitizeFileName(filename) + ".md";
    const filePath = `${folderPath}/${filename}`;
    let content = "";
    const templatePath = this.plugin.settings.templateFile;
    if (templatePath) {
      const templateFile = this.plugin.app.vault.getAbstractFileByPath(templatePath);
      if (templateFile instanceof import_obsidian.TFile) {
        content = await this.plugin.app.vault.read(templateFile);
      } else {
        new import_obsidian.Notice(
          `Template file not found: ${templatePath}. Using default template.`
        );
      }
    }
    if (!content) {
      content = `---
category:
  - "[[Albums]]"
cover: {{coverUrl}}
tags:
  - music
  - albums
  - references
genre: {{genre}}
artist: "[[{{artist}}]]"
year: {{publishYear}}
created: {{date}}
rating: 
---
`;
    }
    for (const key in variables) {
      content = content.replace(new RegExp(key, "g"), variables[key]);
    }
    try {
      const existingFile = this.plugin.app.vault.getAbstractFileByPath(filePath);
      if (existingFile instanceof import_obsidian.TFile) {
        new import_obsidian.Notice(`File ${filename} already exists!`);
        this.plugin.app.workspace.getLeaf().openFile(existingFile);
      } else {
        const newFile = await this.plugin.app.vault.create(
          filePath,
          content
        );
        this.plugin.app.workspace.getLeaf().openFile(newFile);
        new import_obsidian.Notice(`Created ${filename}`);
      }
    } catch (error) {
      console.error("Error creating album note:", error);
      new import_obsidian.Notice("Error creating album note.");
    }
  }
  sanitizeFileName(name) {
    return name.replace(/[\\/:*?"<>|]/g, "").trim();
  }
};
var AlbumSearchSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Album Search Settings" });
    new import_obsidian.Setting(containerEl).setName("Spotify Client ID").setDesc("Your Spotify App Client ID").addText(
      (text) => text.setPlaceholder("Client ID").setValue(this.plugin.settings.spotifyClientId).onChange(async (value) => {
        this.plugin.settings.spotifyClientId = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Spotify Client Secret").setDesc("Your Spotify App Client Secret").addText(
      (text) => text.setPlaceholder("Client Secret").setValue(this.plugin.settings.spotifyClientSecret).onChange(async (value) => {
        this.plugin.settings.spotifyClientSecret = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Folder location").setDesc("Folder to store new album notes").addText(
      (text) => text.setPlaceholder("Albums").setValue(this.plugin.settings.folder).onChange(async (value) => {
        this.plugin.settings.folder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("File Name Format").setDesc("Available variables: {{title}}, {{artist}}, {{year}}").addText(
      (text) => text.setPlaceholder("{{title}}").setValue(this.plugin.settings.fileNameFormat).onChange(async (value) => {
        this.plugin.settings.fileNameFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Template File").setDesc("Path to template file.").addText(
      (text) => text.setPlaceholder("Templates/Album Template.md").setValue(this.plugin.settings.templateFile).onChange(async (value) => {
        this.plugin.settings.templateFile = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
